### ISSUE TITLE
Text Sensor

### ISSUE THREAD

**Issue by cg089** [jplitza/esphome-obis-sensor#7]
Danke für das tolle Plugin. Habe ewig gebraucht um festzustellen, dass mein Smart Meter kein SML spricht.
Da geht die Entwicklung für ESPHome auch grade zügig voran:
https://github.com/alengwenus/esphome_components/blob/main/components/sml/README.md

Eine Idee aber für dieses Plugin: Das Smart Meter wirft noch allerhand weitere Daten aus, die man mit einem Text Sensor abgreifen könnte (Zählernummer etc). Könnte man text_sensor noch reinimplentieren?

Herzliche Grüße!

**Comment by jplitza** [comment]
Habe ich in e149c06 implementiert.
